from collections.abc import Callable
from datetime import datetime
from typing import Literal, Protocol

from cofrap.domain.models import User

TokenPurpose = Literal["delivery", "enrollment", "renewal", "session"]
Clock = Callable[[], datetime]


class UserRepository(Protocol):
    def by_username(self, username: str) -> User | None: ...
    def by_token(self, purpose: TokenPurpose, digest: str) -> User | None: ...
    def add(self, user: User) -> None: ...
    def save(self, user: User) -> None: ...


class UnitOfWork(Protocol):
    users: UserRepository

    def __enter__(self) -> "UnitOfWork": ...
    def __exit__(self, exc_type, exc_value, traceback) -> None: ...


class Security(Protocol):
    def generate_password(self) -> str: ...
    def hash_password(self, password: str) -> str: ...
    def verify_password(self, password_hash: str, password: str) -> bool: ...
    def encrypt(self, value: str) -> str: ...
    def decrypt(self, value: str) -> str: ...
    def token(self) -> str: ...
    def digest(self, value: str) -> str: ...
    def totp_secret(self) -> str: ...
    def provisioning_uri(self, secret: str, username: str) -> str: ...
    def verify_totp(
        self, secret: str, code: str, now: datetime, last_step: int | None
    ) -> int | None: ...
