events {}
http {
    access_log off;
    server {
        listen 8080;
        proxy_read_timeout 60s;
        location /function/generate-password/ {
            proxy_pass http://generate-password:8080/;
        }
        location /function/generate-2fa/ {
            proxy_pass http://generate-2fa:8080/;
        }
        location /function/authenticate/ {
            proxy_pass http://authenticate:8080/;
        }
    }
}
